backend: local
backup_directory: .
local-config: {tmp_dir: "/home/osboxes/Documents/agent_tmp"}
mongo_opt:
    database: INGInious
    host: localhost
plugins:
  - plugin_module: "inginious-problems-blockly"
superadmins:
- superadmin
tasks_directory: .
use_minified_js: true